---
name: Luca Capella Klein
qualifications: Econ, BSc
address: São Paulo - SP | 27 anos
phone: +55 11 98403-4661
email: lucacklein@gmailcom
github: lcklein
linkedin: luca-klein-b118b2128
headcolor: "414141"
output: 
  vitae::awesomecv:
    keep_tex: true
---

```{r setup, include = FALSE}

# libPaths("C:/Users/LucaKlein/4intelligence/Regional - Documentos/Regional/trabalho/pib_regional/renv/library/R-40/x86_64-w64-mingw32/")
# 
# source("C:/Users/LucaKlein/Documents/modelagem-em-escala/auxiliary_functions/packagesR")
library(vitae)
library(tidyverse)
library(vitae)
knitr::opts_chunk$set(echo = FALSE)
```

# Educação

```{r education}

tribble(
  ~ grau, ~ universidade, ~ local, ~ datas,
 "Cedeplar/ UFMG", "Belo Horizonte, Brasil", "Mestrado, Economia","Jan 2022 - Presente",
   "Pontifícia Universidade Católica de São Paulo", "São Paulo, Brasil", "Bacharelado, Economia","Jan 2015 - Dez 2019"
) %>% 
  detailed_entries(grau, datas, local, universidade)


```

# Experiência Acadêmica

```{r research}

tribble(~ papel, ~ empresa, ~ local, ~ datas, ~ detalhes,
"Assistente de Pesquisa","Jul 2023 - Presente", "The Effects of Fiscal Stimulus– Evidence from a New Narrative Measure" ,"Trabalho Remoto", "Análise de documentos de políticas da OCDE, FMI e fontes domésticas",
"Assistente de Pesquisa","Jul 2023 - Presente", "The Effects of Fiscal Stimulus– Evidence from a New Narrative Measure","Trabalho Remoto", "Classificação de episódios de expansão fiscal em economias industrializadas e latino-americanas") %>% 
  detailed_entries(papel, empresa, local ,datas, detalhes)



```

# Histórico de Emprego

```{r consulting}
tribble(
  ~ papel, ~ empresa, ~ local, ~ datas, ~ detalhes,
"Analista Júnior de Economia Regional", "4intelligence", "São Paulo, Brasil", "Jan 2020 - Dez 2020", "Integração de dados espaciais, macroeconômicos e outros em escala regional (região, Estado e outros)",
"Analista Júnior de Economia Regional", "4intelligence", "São Paulo, Brasil", "Jan 2020 - Dez 2020", "Desenvolvimento de abordagens para estimar impactos de políticas econômicas em escala regional",
"Analista Júnior de Economia Regional", "4intelligence", "São Paulo, Brasil", "Jan 2020 - Dez 2020", "Conexão da perspectiva regional aos principais indicadores macroeconômicos brasileiros",
"Analista Júnior de Economia Regional", "4intelligence", "São Paulo, Brasil", "Jan 2020 - Dez 2020", "Condução da análise e previsões do PIB Regional",
"Analista Júnior de Economia Regional", "4intelligence", "São Paulo, Brasil", "Jan 2020 - Dez 2020", "Liderança na pesquisa e condução de análises robustas sobre temas de economia regional",
"Estagiário de Pesquisa Macroeconômica", "4E Consultoria", "São Paulo, Brasil", "Jul 2018 - Dez 2019", "Desenvolvimento de modelos econométricos para previsão de séries temporais",
"Estagiário de Pesquisa Macroeconômica", "4E Consultoria", "São Paulo, Brasil", "Jul 2018 - Dez 2019", "Assistência no desenvolvimento de projetos",
"Estagiário de Pesquisa Macroeconômica", "4E Consultoria", "São Paulo, Brasil", "Jul 2018 - Dez 2019", "Monitoramento de atividade econômica, inflação, indicadores fiscais e internacionais",
"Estagiário de Pesquisa Macroeconômica", "4E Consultoria", "São Paulo, Brasil", "Jul 2018 - Dez 2019", "Manutenção de bancos de dados de índices macroeconômicos selecionados",
"Estagiário em Finanças e Contabilidade", "Colgate-Palmolive", "São Paulo, Brasil", "Jan 2017 - Jul 2018", "Conciliações de patrimônio e contas",
"Estagiário em Finanças e Contabilidade", "Colgate-Palmolive", "São Paulo, Brasil", "Jan 2017 - Jul 2018", "Cálculo de receitas",
"Estagiário em Finanças e Contabilidade", "Colgate-Palmolive", "São Paulo, Brasil", "Jan 2017 - Jul 2018", "Apoio nas demonstrações financeiras",
"Estagiário em Finanças", "Projeto Integrado Comunicação Estratégica", "São Paulo, Brasil", "Jul 2015 - Dez 2015", "Análise do cenário de mercado em escala global",
"Estagiário em Finanças", "Projeto Integrado Comunicação Estratégica", "São Paulo, Brasil", "Jul 2015 - Dez 2015", "Análise de oportunidades para exportação de serviços",
"Estagiário em Finanças", "Projeto Integrado Comunicação Estratégica", "São Paulo, Brasil", "Jul 2015 - Dez 2015", "Contabilidade de responsabilidades"
) %>% 
  detailed_entries(papel, datas, empresa, local, detalhes)
```

# Softwares

```{r softwares}
tribble(
  ~ software, ~ status,
  "R", "Avançado ",
  "Python", "Básico ",
  "Office 365","Avançado",
  "LaTeX", "Básico",
)  %>% 
  detailed_entries(software, status)

```

# Idiomas

```{r lang}

tribble(
  ~ idioma, ~ status,
  "Português","Nativo",
  "Inglês", "Avançado "
)  %>% 
  detailed_entries(idioma, status)

```
